In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
heart_data = pd.read_csv("Heart_Disease_Prediction.csv")
heart_data.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [5]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
Age                        270 non-null int64
Sex                        270 non-null int64
Chest pain type            270 non-null int64
BP                         270 non-null int64
Cholesterol                270 non-null int64
FBS over 120               270 non-null int64
EKG results                270 non-null int64
Max HR                     270 non-null int64
Exercise angina            270 non-null int64
ST depression              270 non-null float64
Slope of ST                270 non-null int64
Number of vessels fluro    270 non-null int64
Thallium                   270 non-null int64
Heart Disease              270 non-null object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.6+ KB

In [6]:
heart_data.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [7]:
heart_data.describe()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
count,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.000000,270.00000,270.000000,270.000000,270.000000
mean,54.433333,0.677778,3.174074,131.344444,249.659259,0.148148,1.022222,149.677778,0.329630,1.05000,1.585185,0.670370,4.696296
std,9.109067,0.468195,0.950090,17.861608,51.686237,0.355906,0.997891,23.165717,0.470952,1.14521,0.614390,0.943896,1.940659
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.00000,1.000000,0.000000,3.000000
25%,48.000000,0.000000,3.000000,120.000000,213.000000,0.000000,0.000000,133.000000,0.000000,0.00000,1.000000,0.000000,3.000000
50%,55.000000,1.000000,3.000000,130.000000,245.000000,0.000000,2.000000,153.500000,0.000000,0.80000,2.000000,0.000000,3.000000
75%,61.000000,1.000000,4.000000,140.000000,280.000000,0.000000,2.000000,166.000000,1.000000,1.60000,2.000000,1.000000,7.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.20000,3.000000,3.000000,7.000000

In [8]:
heart_data['Heart Disease'].value_counts()

Absence     150
Presence    120
Name: Heart Disease, dtype: int64

Absence --> healthy heart
Presence --> diseased heart

In [9]:
x = heart_data.drop(columns='Heart Disease',axis=1)
y = heart_data['Heart Disease']

In [10]:
print(x)

     Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0     70    1                4  130          322             0            2
1     67    0                3  115          564             0            2
2     57    1                2  124          261             0            0
3     64    1                4  128          263             0            0
4     74    0                2  120          269             0            2
5     65    1                4  120          177             0            0
6     56    1                3  130          256             1            2
7     59    1                4  110          239             0            2
8     60    1                4  140          293             0            2
9     63    0                4  150          407             0            2
10    59    1                4  135          234             0            0
11    53    1                4  142          226             0            2
12    44    1                3  140          235             0            2
13    61    1                1  134          234             0            0
14    57    0                4  128          303             0            2
15    71    0                4  112          149             0            0
16    46    1                4  140          311             0            0
17    53    1                4  140          203             1            2
18    64    1                1  110          211             0            2
19    40    1                1  140          199             0            0
20    67    1                4  120          229             0            2
21    48    1                2  130          245             0            2
22    43    1                4  115          303             0            0
23    47    1                4  112          204             0            0
24    54    0                2  132          288             1            2
25    48    0                3  130          275             0            0
26    46    0                4  138          243             0            2
27    51    0                3  120          295             0            2
28    58    1                3  112          230             0            2
29    71    0                3  110          265             1            2
..   ...  ...              ...  ...          ...           ...          ...
240   68    1                3  180          274             1            2
241   39    1                3  140          321             0            2
242   53    0                4  130          264             0            2
243   62    0                4  140          268             0            2
244   51    0                3  140          308             0            2
245   60    1                4  130          253             0            0
246   65    1                4  110          248             0            2
247   65    0                3  155          269             0            0
248   60    1                3  140          185             0            2
249   60    1                4  145          282             0            2
250   54    1                4  120          188             0            0
251   44    1                2  130          219             0            2
252   44    1                4  112          290             0            2
253   51    1                3  110          175             0            0
254   59    1                3  150          212             1            0
255   71    0                2  160          302             0            0
256   61    1                3  150          243             1            0
257   55    1                4  132          353             0            0
258   64    1                3  140          335             0            0
259   43    1                4  150          247             0            0
260   58    0                3  120          340             0            0
261   60    1                4  130          206             0            2
262   58    1                2  120          284             0            2
263   49    1                2  130          266             0            0
264   48    1                2  110          229             0            0
265   52    1                3  172          199             1            0
266   44    1                2  120          263             0            0
267   56    0                2  140          294             0            2
268   57    1                4  140          192             0            0
269   67    1                4  160          286             0            2

     Max HR  Exercise angina  ST depression  Slope of ST  \
0       109                0            2.4            2
1       160                0            1.6            2
2       141                0            0.3            1
3       105                1            0.2            2
4       121                1            0.2            1
5       140                0            0.4            1
6       142                1            0.6            2
7       142                1            1.2            2
8       170                0            1.2            2
9       154                0            4.0            2
10      161                0            0.5            2
11      111                1            0.0            1
12      180                0            0.0            1
13      145                0            2.6            2
14      159                0            0.0            1
15      125                0            1.6            2
16      120                1            1.8            2
17      155                1            3.1            3
18      144                1            1.8            2
19      178                1            1.4            1
20      129                1            2.6            2
21      180                0            0.2            2
22      181                0            1.2            2
23      143                0            0.1            1
24      159                1            0.0            1
25      139                0            0.2            1
26      152                1            0.0            2
27      157                0            0.6            1
28      165                0            2.5            2
29      130                0            0.0            1
..      ...              ...            ...          ...
240     150                1            1.6            2
241     182                0            0.0            1
242     143                0            0.4            2
243     160                0            3.6            3
244     142                0            1.5            1
245     144                1            1.4            1
246     158                0            0.6            1
247     148                0            0.8            1
248     155                0            3.0            2
249     142                1            2.8            2
250     113                0            1.4            2
251     188                0            0.0            1
252     153                0            0.0            1
253     123                0            0.6            1
254     157                0            1.6            1
255     162                0            0.4            1
256     137                1            1.0            2
257     132                1            1.2            2
258     158                0            0.0            1
259     171                0            1.5            1
260     172                0            0.0            1
261     132                1            2.4            2
262     160                0            1.8            2
263     171                0            0.6            1
264     168                0            1.0            3
265     162                0            0.5            1
266     173                0            0.0            1
267     153                0            1.3            2
268     148                0            0.4            2
269     108                1            1.5            2

     Number of vessels fluro  Thallium
0                          3         3
1                          0         7
2                          0         7
3                          1         7
4                          1         3
5                          0         7
6                          1         6
7                          1         7
8                          2         7
9                          3         7
10                         0         7
11                         0         7
12                         0         3
13                         2         3
14                         1         3
15                         0         3
16                         2         7
17                         0         7
18                         0         3
19                         0         7
20                         2         7
21                         0         3
22                         0         3
23                         0         3
24                         1         3
25                         0         3
26                         0         3
27                         0         3
28                         1         7
29                         1         3
..                       ...       ...
240                        0         7
241                        0         3
242                        0         3
243                        2         3
244                        1         3
245                        1         7
246                        2         6
247                        0         3
248                        0         3
249                        2         7
250                        1         7
251                        0         3
252                        1         3
253                        0         3
254                        0         3
255                        2         3
256                        0         3
257                        1         7
258                        0         3
259                        0         3
260                        0         3
261                        2         7
262                        0         3
263                        0         3
264                        0         7
265                        0         7
266                        0         7
267                        0         3
268                        0         6
269                        3         3

[270 rows x 13 columns]

In [11]:
print(y)

0      Presence
1       Absence
2      Presence
3       Absence
4       Absence
5       Absence
6      Presence
7      Presence
8      Presence
9      Presence
10      Absence
11      Absence
12      Absence
13     Presence
14      Absence
15      Absence
16     Presence
17     Presence
18      Absence
19      Absence
20     Presence
21      Absence
22      Absence
23      Absence
24      Absence
25      Absence
26      Absence
27      Absence
28     Presence
29      Absence
         ...
240    Presence
241     Absence
242     Absence
243    Presence
244     Absence
245    Presence
246    Presence
247     Absence
248    Presence
249    Presence
250    Presence
251     Absence
252    Presence
253     Absence
254     Absence
255     Absence
256     Absence
257    Presence
258    Presence
259     Absence
260     Absence
261    Presence
262    Presence
263     Absence
264    Presence
265     Absence
266     Absence
267     Absence
268     Absence
269    Presence
Name: Heart Disease, Length: 270, dtype: object

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [13]:
print(x.shape,x_train.shape,x_test.shape)

(270, 13) (216, 13) (54, 13)

In [14]:
model = LogisticRegression()

In [15]:
model.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [17]:
print(('Accuracy on Training data: ',training_data_accuracy))

('Accuracy on Training data: ', 0.8796296296296297)

In [18]:
x_train_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_train_prediction,y_test)

In [19]:
print(('Accuracy on Test data: ',test_data_accuracy))

('Accuracy on Test data: ', 0.8148148148148148)

Building Predictive System

In [29]:
input_data = (63,0,4,150,407,0,2,154,0,4,2,3,7)

#change input data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

#reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction[0] == 'Presence'):
    print("The person has a heart disease")
else:
    print("The person's heart is healthy")

['Presence']
The person has a heart disease